version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: zezman-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: zezman
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - zezman-network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: zezman-server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/zezman?authSource=admin
      PORT: 5000
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      GOOGLE_MAPS_API_KEY: your-google-maps-api-key
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: debug
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/logs:/app/logs
      - ./server/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - zezman-network
    command: npm run dev

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: zezman-client
    restart: unless-stopped
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:5000/api/v1
      REACT_APP_GOOGLE_MAPS_API_KEY: your-google-maps-api-key
      REACT_APP_GOOGLE_CLIENT_ID: your-google-client-id
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - zezman-network
    command: npm start

  # Redis for caching and sessions (optional)
  redis:
    image: redis:7-alpine
    container_name: zezman-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zezman-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  zezman-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Health checks
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s 